name: Retrain Model

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly retraining
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Retrain model
      env:
        DATA_PATH: data/winequality-red.csv
      run: |
        poetry run python src/retrain_model.py
